//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Builder.Presentation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AbilitiesGenerationOption {
            get {
                return ((int)(this["AbilitiesGenerationOption"]));
            }
            set {
                this["AbilitiesGenerationOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aurora Default")]
        public string Accent {
            get {
                return ((string)(this["Accent"]));
            }
            set {
                this["Accent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string AdditionalCustomDirectory {
            get {
                return ((string)(this["AdditionalCustomDirectory"]));
            }
            set {
                this["AdditionalCustomDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowEditableSheet {
            get {
                return ((bool)(this["AllowEditableSheet"]));
            }
            set {
                this["AllowEditableSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyDefaultSourceRestrictionsOnNewCharacter {
            get {
                return ((bool)(this["ApplyDefaultSourceRestrictionsOnNewCharacter"]));
            }
            set {
                this["ApplyDefaultSourceRestrictionsOnNewCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoNavigateNextSelectionWhenAvailable {
            get {
                return ((bool)(this["AutoNavigateNextSelectionWhenAvailable"]));
            }
            set {
                this["AutoNavigateNextSelectionWhenAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bundle {
            get {
                return ((bool)(this["Bundle"]));
            }
            set {
                this["Bundle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CharacterPanelAbilityScoresExpanded {
            get {
                return ((bool)(this["CharacterPanelAbilityScoresExpanded"]));
            }
            set {
                this["CharacterPanelAbilityScoresExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CharacterPanelQuickActionsExpanded {
            get {
                return ((bool)(this["CharacterPanelQuickActionsExpanded"]));
            }
            set {
                this["CharacterPanelQuickActionsExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterPanelSavingThrowsExpanded {
            get {
                return ((bool)(this["CharacterPanelSavingThrowsExpanded"]));
            }
            set {
                this["CharacterPanelSavingThrowsExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CharacterPanelSkillsExpanded {
            get {
                return ((bool)(this["CharacterPanelSkillsExpanded"]));
            }
            set {
                this["CharacterPanelSkillsExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CharacterPanelStatisticsExpanded {
            get {
                return ((bool)(this["CharacterPanelStatisticsExpanded"]));
            }
            set {
                this["CharacterPanelStatisticsExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int CharactersCollectionSize {
            get {
                return ((int)(this["CharactersCollectionSize"]));
            }
            set {
                this["CharactersCollectionSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterSheetAbilitiesFlipped {
            get {
                return ((bool)(this["CharacterSheetAbilitiesFlipped"]));
            }
            set {
                this["CharacterSheetAbilitiesFlipped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CharacterSheetOpenOnSave {
            get {
                return ((bool)(this["CharacterSheetOpenOnSave"]));
            }
            set {
                this["CharacterSheetOpenOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfigurationUpgradeRequired {
            get {
                return ((bool)(this["ConfigurationUpgradeRequired"]));
            }
            set {
                this["ConfigurationUpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string DefaultFontSize {
            get {
                return ((string)(this["DefaultFontSize"]));
            }
            set {
                this["DefaultFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string DefaultSourceRestrictions {
            get {
                return ((string)(this["DefaultSourceRestrictions"]));
            }
            set {
                this["DefaultSourceRestrictions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayRemoveLevelConfirmation {
            get {
                return ((bool)(this["DisplayRemoveLevelConfirmation"]));
            }
            set {
                this["DisplayRemoveLevelConfirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplaySelectionExpanderColumnHeaders {
            get {
                return ((bool)(this["DisplaySelectionExpanderColumnHeaders"]));
            }
            set {
                this["DisplaySelectionExpanderColumnHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string DocumentsRootDirectory {
            get {
                return ((string)(this["DocumentsRootDirectory"]));
            }
            set {
                this["DocumentsRootDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateSheetOnCharacterChangedRegistered {
            get {
                return ((bool)(this["GenerateSheetOnCharacterChangedRegistered"]));
            }
            set {
                this["GenerateSheetOnCharacterChangedRegistered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeItemcards {
            get {
                return ((bool)(this["IncludeItemcards"]));
            }
            set {
                this["IncludeItemcards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeSpellcards {
            get {
                return ((bool)(this["IncludeSpellcards"]));
            }
            set {
                this["IncludeSpellcards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MaximumAbilityBaseScore {
            get {
                return ((int)(this["MaximumAbilityBaseScore"]));
            }
            set {
                this["MaximumAbilityBaseScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinimumAbilityBaseScore {
            get {
                return ((int)(this["MinimumAbilityBaseScore"]));
            }
            set {
                this["MinimumAbilityBaseScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Patreon {
            get {
                return ((bool)(this["Patreon"]));
            }
            set {
                this["Patreon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Player One")]
        public string PlayerName {
            get {
                return ((string)(this["PlayerName"]));
            }
            set {
                this["PlayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickSearchBarEnabled {
            get {
                return ((bool)(this["QuickSearchBarEnabled"]));
            }
            set {
                this["QuickSearchBarEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequestAddAttackWhenEquippingWeapon {
            get {
                return ((bool)(this["RequestAddAttackWhenEquippingWeapon"]));
            }
            set {
                this["RequestAddAttackWhenEquippingWeapon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchMissingSourceOnline {
            get {
                return ((bool)(this["SearchMissingSourceOnline"]));
            }
            set {
                this["SearchMissingSourceOnline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int SelectionExpanderGridRowSize {
            get {
                return ((int)(this["SelectionExpanderGridRowSize"]));
            }
            set {
                this["SelectionExpanderGridRowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetDescriptionAbbreviateUsage {
            get {
                return ((bool)(this["SheetDescriptionAbbreviateUsage"]));
            }
            set {
                this["SheetDescriptionAbbreviateUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SheetFormattingActionSuffixBold {
            get {
                return ((bool)(this["SheetFormattingActionSuffixBold"]));
            }
            set {
                this["SheetFormattingActionSuffixBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetFormFillable {
            get {
                return ((bool)(this["SheetFormFillable"]));
            }
            set {
                this["SheetFormFillable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetIncludeAttackCards {
            get {
                return ((bool)(this["SheetIncludeAttackCards"]));
            }
            set {
                this["SheetIncludeAttackCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetIncludeFeatureCards {
            get {
                return ((bool)(this["SheetIncludeFeatureCards"]));
            }
            set {
                this["SheetIncludeFeatureCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SheetIncludeFormatting {
            get {
                return ((bool)(this["SheetIncludeFormatting"]));
            }
            set {
                this["SheetIncludeFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetIncludeItemCards {
            get {
                return ((bool)(this["SheetIncludeItemCards"]));
            }
            set {
                this["SheetIncludeItemCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SheetIncludeNonPreparedSpells {
            get {
                return ((bool)(this["SheetIncludeNonPreparedSpells"]));
            }
            set {
                this["SheetIncludeNonPreparedSpells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SheetIncludeSpellCards {
            get {
                return ((bool)(this["SheetIncludeSpellCards"]));
            }
            set {
                this["SheetIncludeSpellCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetStartAttackCardsOnNewPage {
            get {
                return ((bool)(this["SheetStartAttackCardsOnNewPage"]));
            }
            set {
                this["SheetStartAttackCardsOnNewPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SheetStartFeatureCardsOnNewPage {
            get {
                return ((bool)(this["SheetStartFeatureCardsOnNewPage"]));
            }
            set {
                this["SheetStartFeatureCardsOnNewPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SheetStartItemCardsOnNewPage {
            get {
                return ((bool)(this["SheetStartItemCardsOnNewPage"]));
            }
            set {
                this["SheetStartItemCardsOnNewPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetStartSpellCardsOnNewPage {
            get {
                return ((bool)(this["SheetStartSpellCardsOnNewPage"]));
            }
            set {
                this["SheetStartSpellCardsOnNewPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double ShellWindowHeight {
            get {
                return ((double)(this["ShellWindowHeight"]));
            }
            set {
                this["ShellWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShellWindowLeft {
            get {
                return ((double)(this["ShellWindowLeft"]));
            }
            set {
                this["ShellWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShellWindowState {
            get {
                return ((bool)(this["ShellWindowState"]));
            }
            set {
                this["ShellWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ShellWindowTop {
            get {
                return ((double)(this["ShellWindowTop"]));
            }
            set {
                this["ShellWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double ShellWindowWidth {
            get {
                return ((double)(this["ShellWindowWidth"]));
            }
            set {
                this["ShellWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupCheckForContentUpdated {
            get {
                return ((bool)(this["StartupCheckForContentUpdated"]));
            }
            set {
                this["StartupCheckForContentUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupCheckForUpdates {
            get {
                return ((bool)(this["StartupCheckForUpdates"]));
            }
            set {
                this["StartupCheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupLoadCustomFiles {
            get {
                return ((bool)(this["StartupLoadCustomFiles"]));
            }
            set {
                this["StartupLoadCustomFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aurora Dark")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDefaultAbilityScoreMaximum {
            get {
                return ((bool)(this["UseDefaultAbilityScoreMaximum"]));
            }
            set {
                this["UseDefaultAbilityScoreMaximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLegactBackgroundPage {
            get {
                return ((bool)(this["UseLegactBackgroundPage"]));
            }
            set {
                this["UseLegactBackgroundPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLegacyDetailsPage {
            get {
                return ((bool)(this["UseLegacyDetailsPage"]));
            }
            set {
                this["UseLegacyDetailsPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLegacySpellcastingPage {
            get {
                return ((bool)(this["UseLegacySpellcastingPage"]));
            }
            set {
                this["UseLegacySpellcastingPage"] = value;
            }
        }
    }
}
